# ==============================
# Database Configuration
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/shreya_db
spring.datasource.username=root
spring.datasource.password=Akash@5473
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# Server Port (optional)
# ==============================
server.port=8080

# ==============================
# JWT Secret Key (optional - or use from code)
# ==============================
#jwt.secret=secret-key

# ==============================
# Spring Security
# ==============================
spring.security.users.name=demo
spring.security.users.password={noop}demo

